version: 2
jobs:
    build:
        docker:
            - image: nicolov/bazel-buildroot-toolchain:0.0.1
        steps:
            - checkout
            - run: ./build.sh
            - store_artifacts:
                path: /tmp/artifacts
